import { CrustdataPersonProfile } from "@/shared/models/built-in-integrations/crustdata";

export const fakeCrustdataPersonProfile: CrustdataPersonProfile[] = [
  {
    linkedin_profile_url: "https://linkedin.com/in/sarah-johnson-ai",
    linkedin_flagship_url: "https://linkedin.com/in/sarah-johnson-ai",
    name: "Sarah Johnson",
    location: "San Francisco, CA",
    email: "sarah.johnson@techcorp.com",
    title: "Senior AI Engineer",
    last_updated: "2024-01-15T10:30:00Z",
    headline: "AI Engineer | Machine Learning | Python | TensorFlow",
    summary:
      "Passionate AI engineer with 5+ years of experience building scalable machine learning solutions. Specialized in computer vision and natural language processing.",
    num_of_connections: 847,
    profile_picture_url: "https://example.com/profiles/sarah-johnson.jpg",
    profile_picture_permalink: "https://example.com/profiles/sarah-johnson-permalink",
    twitter_handle: "@sarah_ai_engineer",
    languages: ["English", "Spanish"],
    enriched_realtime: true,
    business_email: ["sarah.johnson@techcorp.com", "sarah.j@ai-startup.io"],
    query_linkedin_profile_urn_or_slug: ["urn:li:fsd_profile:ACoAABc1234"],
    skills: ["Python", "TensorFlow", "PyTorch", "Computer Vision", "NLP", "AWS", "Docker"],
    all_employers_company_id: [12345, 67890],
    all_titles: ["AI Engineer", "Machine Learning Engineer", "Software Engineer"],
    all_schools: ["Stanford University", "MIT"],
    all_degrees: ["Master of Science in Computer Science", "Bachelor of Science in Mathematics"],
    person_id: 1001,
    score: 95,
    current_employers: [
      {
        employer_name: "TechCorp AI",
        employer_linkedin_id: "techcorp-ai",
        employer_logo_url: "https://example.com/logos/techcorp-ai.png",
        employer_linkedin_description: "Leading AI company focused on enterprise solutions",
        employer_company_id: [12345],
        employer_company_website_domain: ["techcorp-ai.com"],
        employee_position_id: 456,
        employee_title: "Senior AI Engineer",
        employee_description: "Leading machine learning initiatives and AI model development",
        employee_location: "San Francisco, CA",
        start_date: "2022-03-01",
      },
    ],
    past_employers: [
      {
        employer_name: "AI Startup Inc",
        employer_linkedin_id: "ai-startup-inc",
        employer_logo_url: "https://example.com/logos/ai-startup.png",
        employer_linkedin_description: "Innovative startup in artificial intelligence",
        employer_company_id: [67890],
        employer_company_website_domain: ["ai-startup.io"],
        employee_position_id: 789,
        employee_title: "Machine Learning Engineer",
        employee_description: "Developed computer vision models for autonomous systems",
        employee_location: "Palo Alto, CA",
        start_date: "2020-06-01",
        end_date: "2022-02-28",
      },
    ],
    education_background: [
      {
        degree_name: "Master of Science in Computer Science",
        institute_name: "Stanford University",
        institute_linkedin_id: "stanford-university",
        institute_linkedin_url: "https://linkedin.com/school/stanford-university",
        institute_logo_url: "https://example.com/logos/stanford.png",
        field_of_study: "Computer Science",
        activities_and_societies: "AI Research Group, Women in CS",
        start_date: "2018-09-01",
        end_date: "2020-06-01",
      },
      {
        degree_name: "Bachelor of Science in Mathematics",
        institute_name: "MIT",
        institute_linkedin_id: "mit",
        institute_linkedin_url: "https://linkedin.com/school/mit",
        institute_logo_url: "https://example.com/logos/mit.png",
        field_of_study: "Mathematics",
        activities_and_societies: "Math Club, Research Assistant",
        start_date: "2014-09-01",
        end_date: "2018-06-01",
      },
    ],
  },
  {
    linkedin_profile_url: "https://linkedin.com/in/michael-chen-dev",
    linkedin_flagship_url: "https://linkedin.com/in/michael-chen-dev",
    name: "Michael Chen",
    location: "New York, NY",
    email: "michael.chen@fintech.com",
    title: "Full Stack Developer",
    last_updated: "2024-01-10T14:20:00Z",
    headline: "Full Stack Developer | React | Node.js | TypeScript",
    summary:
      "Experienced full stack developer passionate about building robust web applications and scalable backend systems.",
    num_of_connections: 623,
    profile_picture_url: "https://example.com/profiles/michael-chen.jpg",
    profile_picture_permalink: "https://example.com/profiles/michael-chen-permalink",
    twitter_handle: "@mchen_dev",
    languages: ["English", "Mandarin"],
    enriched_realtime: false,
    business_email: ["michael.chen@fintech.com"],
    query_linkedin_profile_urn_or_slug: ["urn:li:fsd_profile:ACoAABd5678"],
    skills: ["React", "Node.js", "TypeScript", "JavaScript", "PostgreSQL", "MongoDB", "AWS"],
    all_employers_company_id: [11111, 22222],
    all_titles: ["Full Stack Developer", "Frontend Developer", "Software Engineer"],
    all_schools: ["NYU", "Columbia University"],
    all_degrees: ["Bachelor of Science in Computer Science"],
    person_id: 1002,
    score: 87,
    current_employers: [
      {
        employer_name: "FinTech Solutions",
        employer_linkedin_id: "fintech-solutions",
        employer_logo_url: "https://example.com/logos/fintech-solutions.png",
        employer_linkedin_description: "Innovative financial technology company",
        employer_company_id: [11111],
        employer_company_website_domain: ["fintech.com"],
        employee_position_id: 123,
        employee_title: "Full Stack Developer",
        employee_description: "Building modern web applications for financial services",
        employee_location: "New York, NY",
        start_date: "2021-08-01",
      },
    ],
    past_employers: [
      {
        employer_name: "WebDev Agency",
        employer_linkedin_id: "webdev-agency",
        employer_logo_url: "https://example.com/logos/webdev-agency.png",
        employer_linkedin_description: "Digital agency specializing in web development",
        employer_company_id: [22222],
        employer_company_website_domain: ["webdev-agency.com"],
        employee_position_id: 456,
        employee_title: "Frontend Developer",
        employee_description: "Developed responsive websites and web applications",
        employee_location: "New York, NY",
        start_date: "2019-01-01",
        end_date: "2021-07-31",
      },
    ],
    education_background: [
      {
        degree_name: "Bachelor of Science in Computer Science",
        institute_name: "NYU",
        institute_linkedin_id: "nyu",
        institute_linkedin_url: "https://linkedin.com/school/nyu",
        institute_logo_url: "https://example.com/logos/nyu.png",
        field_of_study: "Computer Science",
        activities_and_societies: "CS Club, Hackathon Organizer",
        start_date: "2015-09-01",
        end_date: "2019-05-01",
      },
    ],
  },
  {
    linkedin_profile_url: "https://linkedin.com/in/emma-rodriguez-marketing",
    linkedin_flagship_url: "https://linkedin.com/in/emma-rodriguez-marketing",
    name: "Emma Rodriguez",
    location: "Austin, TX",
    email: "emma.rodriguez@growthmarketing.com",
    title: "Marketing Director",
    last_updated: "2024-01-12T09:15:00Z",
    headline: "Marketing Director | Growth Marketing | Digital Strategy | Brand Development",
    summary:
      "Strategic marketing leader with expertise in growth marketing, brand development, and digital transformation. Proven track record of scaling businesses through innovative marketing strategies.",
    num_of_connections: 1247,
    profile_picture_url: "https://example.com/profiles/emma-rodriguez.jpg",
    profile_picture_permalink: "https://example.com/profiles/emma-rodriguez-permalink",
    twitter_handle: "@emma_marketing",
    languages: ["English", "Spanish", "Portuguese"],
    enriched_realtime: true,
    business_email: ["emma.rodriguez@growthmarketing.com", "emma@emma-rodriguez.com"],
    query_linkedin_profile_urn_or_slug: ["urn:li:fsd_profile:ACoAABe9012"],
    skills: [
      "Growth Marketing",
      "Digital Marketing",
      "Brand Strategy",
      "Google Analytics",
      "HubSpot",
      "Social Media Marketing",
      "Content Marketing",
    ],
    all_employers_company_id: [33333, 44444, 55555],
    all_titles: ["Marketing Director", "Senior Marketing Manager", "Marketing Specialist"],
    all_schools: ["University of Texas", "University of Miami"],
    all_degrees: ["Master of Business Administration", "Bachelor of Arts in Marketing"],
    person_id: 1003,
    score: 92,
    current_employers: [
      {
        employer_name: "Growth Marketing Co",
        employer_linkedin_id: "growth-marketing-co",
        employer_logo_url: "https://example.com/logos/growth-marketing-co.png",
        employer_linkedin_description: "Full-service growth marketing agency",
        employer_company_id: [33333],
        employer_company_website_domain: ["growthmarketing.com"],
        employee_position_id: 789,
        employee_title: "Marketing Director",
        employee_description: "Leading marketing strategy and team for multiple client accounts",
        employee_location: "Austin, TX",
        start_date: "2023-01-01",
      },
    ],
    past_employers: [
      {
        employer_name: "Tech Startup XYZ",
        employer_linkedin_id: "tech-startup-xyz",
        employer_logo_url: "https://example.com/logos/tech-startup-xyz.png",
        employer_linkedin_description: "B2B SaaS startup focused on productivity tools",
        employer_company_id: [44444],
        employer_company_website_domain: ["techstartupxyz.com"],
        employee_position_id: 101,
        employee_title: "Senior Marketing Manager",
        employee_description: "Managed digital marketing campaigns and brand development",
        employee_location: "Austin, TX",
        start_date: "2020-03-01",
        end_date: "2022-12-31",
      },
      {
        employer_name: "Global Brands Inc",
        employer_linkedin_id: "global-brands-inc",
        employer_logo_url: "https://example.com/logos/global-brands-inc.png",
        employer_linkedin_description: "International consumer goods company",
        employer_company_id: [55555],
        employer_company_website_domain: ["globalbrands.com"],
        employee_position_id: 202,
        employee_title: "Marketing Specialist",
        employee_description: "Executed marketing campaigns and social media strategies",
        employee_location: "Miami, FL",
        start_date: "2018-06-01",
        end_date: "2020-02-29",
      },
    ],
    education_background: [
      {
        degree_name: "Master of Business Administration",
        institute_name: "University of Texas",
        institute_linkedin_id: "university-of-texas",
        institute_linkedin_url: "https://linkedin.com/school/university-of-texas",
        institute_logo_url: "https://example.com/logos/ut.png",
        field_of_study: "Business Administration",
        activities_and_societies: "Marketing Association, Business Club",
        start_date: "2016-09-01",
        end_date: "2018-05-01",
      },
      {
        degree_name: "Bachelor of Arts in Marketing",
        institute_name: "University of Miami",
        institute_linkedin_id: "university-of-miami",
        institute_linkedin_url: "https://linkedin.com/school/university-of-miami",
        institute_logo_url: "https://example.com/logos/um.png",
        field_of_study: "Marketing",
        activities_and_societies: "Marketing Society, Hispanic Student Association",
        start_date: "2014-09-01",
        end_date: "2018-05-01",
      },
    ],
  },
];
