import type {
  PDLPerson,
  PDLPersonIdentifyData,
  PDLPersonIdentifyResponse,
  PDLPersonResponse,
} from "@/shared/models/built-in-integrations/people-data-labs";

const fakePDLPerson: PDLPerson = {
  id: "1234567890",
  full_name: "test user",
  first_name: "test",
  last_name: "user",
  linkedin_url: "https://www.linkedin.com/in/testuser",
  job_title: "Software Engineer",
  job_company_name: "Test Company",
  location_name: "San Francisco, CA",
  industry: "Technology",
  skills: ["JavaScript", "React", "Node.js"],
};

export const fakePDLPersonResponse: PDLPersonResponse = {
  status: 200,
  likelihood: 10,
  data: fakePDLPerson,
};

export const fakePDLPersonIdentifyData: PDLPersonIdentifyData = {
  id: "jane_doe_123456789",
  full_name: "Jane Doe",
  first_name: "Jane",
  middle_initial: null,
  middle_name: null,
  last_initial: "D",
  last_name: "Doe",
  sex: "Female",
  birth_year: null,
  birth_date: null,
  linkedin_url: "linkedin.com/in/jane-doe-123456789",
  linkedin_username: "jane-doe-123456789",
  linkedin_id: "987654321",
  headline: null,
  facebook_url: null,
  facebook_username: null,
  facebook_id: null,
  twitter_url: null,
  twitter_username: null,
  github_url: null,
  github_username: null,
  work_email: null,
  personal_emails: ["jane.doe@example.com"],
  recommended_personal_email: "jane.doe@example.com",
  mobile_phone: "+15551234567",
  industry: "Technology",
  job_title: "Software Engineer",
  job_title_role: null,
  job_title_sub_role: null,
  job_title_class: null,
  job_title_levels: [],
  job_company_id: "example_company_123",
  job_company_name: "Example Tech Corp",
  job_company_website: null,
  job_company_size: "51-200",
  job_company_founded: 2015,
  job_company_industry: "Technology",
  job_company_linkedin_url: "linkedin.com/company/example-tech-corp",
  job_company_linkedin_id: "123456",
  job_company_facebook_url: null,
  job_company_twitter_url: null,
  job_company_type: "private",
  job_company_ticker: null,
  job_company_location_name: "San Francisco, California, United States",
  job_company_location_locality: "San Francisco",
  job_company_location_metro: null,
  job_company_location_region: "California",
  job_company_location_geo: "37.77,-122.42",
  job_company_location_street_address: "123 Tech Street",
  job_company_location_address_line_2: null,
  job_company_location_postal_code: "94105",
  job_company_location_country: "United States",
  job_company_location_continent: "North America",
  job_company_employee_count: 150,
  job_company_inferred_revenue: "$10m-$50m",
  job_company_12mo_employee_growth_rate: 0,
  job_company_total_funding_raised: null,
  job_last_changed: "2023-06-15",
  job_last_verified: "2025-01-01",
  job_start_date: null,
  job_summary: null,
  location_name: "San Francisco, California, United States",
  location_locality: "San Francisco",
  location_metro: null,
  location_region: "California",
  location_country: "United States",
  location_continent: "North America",
  location_street_address: null,
  location_address_line_2: null,
  location_postal_code: null,
  location_geo: "37.77,-122.42",
  location_last_updated: "2025-01-01",
  linkedin_connections: 500,
  inferred_salary: null,
  inferred_years_experience: null,
  summary: null,
  phone_numbers: ["+15551234567"],
  emails: [
    {
      address: "jane.doe@example.com",
      type: "personal",
    },
  ],
  interests: [],
  skills: [],
  location_names: ["San Francisco, California, United States", "Oakland, California, United States"],
  regions: ["California, United States"],
  countries: ["United States"],
  street_addresses: [],
  experience: [
    {
      company: {
        name: "Example Tech Corp",
        size: "51-200",
        id: "example_company_123",
        founded: 2015,
        industry: "Technology",
        location: {
          name: "San Francisco, California, United States",
          locality: "San Francisco",
          region: "California",
          metro: null,
          country: "United States",
          continent: "North America",
          street_address: "123 Tech Street",
          address_line_2: null,
          postal_code: "94105",
          geo: "37.77,-122.42",
        },
        linkedin_url: "linkedin.com/company/example-tech-corp",
        linkedin_id: "123456",
        facebook_url: null,
        twitter_url: null,
        website: null,
        ticker: null,
        type: "private",
      },
      location_names: [],
      end_date: null,
      start_date: null,
      title: {
        name: "Software Engineer",
        class: null,
        role: null,
        sub_role: null,
        levels: [],
      },
      is_primary: true,
      summary: null,
    },
  ],
  education: [],
  profiles: [
    {
      network: "linkedin",
      id: "987654321",
      url: "linkedin.com/in/jane-doe-123456789",
      username: "jane-doe-123456789",
    },
  ],
  certifications: [],
  languages: [],
  dataset_version: "31.1",
};

export const fakePDLPersonIdentifyResponse: PDLPersonIdentifyResponse = {
  status: 200,
  matches: [
    {
      data: fakePDLPersonIdentifyData,
      match_score: 92,
      matched_on: ["company", "name"],
    },
    {
      data: fakePDLPersonIdentifyData,
      match_score: 5,
      matched_on: ["name"],
    },
  ],
};
